<?php

namespace Database\Seeders;

use App\Models\BankService;
use Illuminate\Database\Seeder;

class BankServiceSeeder extends Seeder
{
    public function run(): void
    {
        $services = [
            // Main Banking Services
            [
                'title' => 'Consumer Finances',
                'description' => 'Personal financing solutions for individuals and families across AJK',
                'icon' => 'CreditCard',
                'products' => [
                    'Advance Salary Scheme - Up to Rs. 30 Lac for salary earners',
                    'Car Finance - Up to Rs. 30 Lac for vehicle purchase',
                    'House Loan - Up to Rs. 10 Million for home construction',
                    'Personal Loan - Quick loans against deposits',
                    'Gold Loan - Up to Rs. 20 Lac against gold ornaments',
                    'Student Loan - Up to Rs. 10 Million for higher studies',
                ],
                'cta_text' => 'Apply for Consumer Finance',
                'cta_link' => '/products/consumer-finances',
                'color' => 'from-blue-600 to-blue-700',
                'benefits' => ['Quick Processing', 'Competitive Rates', 'Flexible Terms', 'Minimal Documentation'],
                'order' => 1,
                'status' => true,
                'service_type' => 'service',
            ],
            [
                'title' => 'Commercial / SME Finances',
                'description' => 'Comprehensive business financing for enterprises in Kashmir',
                'icon' => 'Building2',
                'products' => [
                    'Running Finance - Working capital for business operations',
                    'Auto Finance - Commercial vehicle financing',
                    'Demand Finance - Machinery and equipment purchase',
                    'Construction Finance - Commercial building projects',
                    'Tourism Finance - Tourism infrastructure development',
                    'Trade Finance - Small business working capital',
                ],
                'cta_text' => 'Explore Business Solutions',
                'cta_link' => '/products/commercial-sme-finances',
                'color' => 'from-green-600 to-green-700',
                'benefits' => ['Business Growth Support', 'Flexible Repayment', 'Expert Advisory', 'Sector Specific Solutions'],
                'order' => 2,
                'status' => true,
                'service_type' => 'service',
            ],
            [
                'title' => 'Agriculture Finances',
                'description' => 'Supporting agricultural development and rural economy of AJK',
                'icon' => 'Wheat',
                'products' => [
                    'Agriculture Production Loan - Short term loans for agri inputs',
                    'Agriculture Development Loan - Long term loans for farm assets',
                    'Farm Equipment Finance - Tractors and machinery financing',
                    'Livestock Finance - Dairy, poultry, and livestock development',
                ],
                'cta_text' => 'Support Agriculture Growth',
                'cta_link' => '/products/agriculture-finances',
                'color' => 'from-amber-600 to-amber-700',
                'benefits' => ['Farmer Friendly Terms', 'Seasonal Repayment', 'Low Interest Rates', 'Rural Development Focus'],
                'order' => 3,
                'status' => true,
                'service_type' => 'service',
            ],
            [
                'title' => 'Micro Finances',
                'description' => 'Empowering small entrepreneurs and promoting self-employment',
                'icon' => 'Users',
                'products' => [
                    'Micro Enterprise Loan - Up to Rs. 1 Lac for small businesses',
                    'Desi Murghbani Scheme - Poultry farming for women (Rs. 15-50K)',
                    'Small Business Support - Self-employment opportunities',
                    'Women Entrepreneurship - Special schemes for women',
                ],
                'cta_text' => 'Start Your Enterprise',
                'cta_link' => '/products/micro-finances',
                'color' => 'from-purple-600 to-purple-700',
                'benefits' => ['Easy Access', 'No Collateral Required', 'Community Development', 'Women Empowerment'],
                'order' => 4,
                'status' => true,
                'service_type' => 'service',
            ],

            // Deposit Services
            [
                'title' => 'Deposit Accounts',
                'description' => 'Savings & Current Accounts',
                'icon' => 'Shield',
                'products' => [],
                'cta_text' => 'Open Account',
                'cta_link' => '/products/deposit-accounts',
                'color' => 'from-blue-600 to-blue-800',
                'benefits' => ['Safe deposits', 'Easy access', 'Competitive rates'],
                'order' => 5,
                'status' => true,
                'service_type' => 'deposit',
            ],
            [
                'title' => 'Term Deposits',
                'description' => 'Fixed Deposit Schemes',
                'icon' => 'TrendingUp',
                'products' => [],
                'cta_text' => 'Invest Now',
                'cta_link' => '/products/term-deposit',
                'color' => 'from-green-600 to-green-800',
                'benefits' => ['Higher returns', 'Fixed tenure', 'Guaranteed returns'],
                'order' => 6,
                'status' => true,
                'service_type' => 'deposit',
            ],
            [
                'title' => 'Digital Banking',
                'description' => 'Online & Mobile Banking',
                'icon' => 'Building2',
                'products' => [],
                'cta_text' => 'Get Started',
                'cta_link' => '/services/all-services',
                'color' => 'from-indigo-600 to-indigo-800',
                'benefits' => ['24/7 access', 'Convenient', 'Secure'],
                'order' => 7,
                'status' => true,
                'service_type' => 'deposit',
            ],
            [
                'title' => 'Lockers Facility',
                'description' => 'Safe Deposit Lockers',
                'icon' => 'Home',
                'products' => [],
                'cta_text' => 'Rent Locker',
                'cta_link' => '/services/lockers-facility',
                'color' => 'from-gray-600 to-gray-800',
                'benefits' => ['High security', 'Various sizes', 'Easy access'],
                'order' => 8,
                'status' => true,
                'service_type' => 'deposit',
            ],

            // Statistics
            [
                'title' => 'Branches',
                'description' => 'Physical branch network across AJK providing personalized banking services.',
                'icon' => 'Building2',
                'products' => [],
                'cta_text' => 'Find Branch',
                'cta_link' => '/contact-us',
                'color' => 'from-orange-600 to-orange-800',
                'benefits' => ['Wide network', 'Expert staff', 'Full services', 'Convenient locations'],
                'order' => 9,
                'status' => true,
                'service_type' => 'stat',
                'stat_number' => '87+',
                'stat_label' => 'Branches',
                'stat_description' => 'Across AJK',
            ],
            [
                'title' => 'Customers',
                'description' => 'Serving thousands of satisfied customers with quality banking services.',
                'icon' => 'Users',
                'products' => [],
                'cta_text' => 'Join Us',
                'cta_link' => '/contact-us',
                'color' => 'from-teal-600 to-teal-800',
                'benefits' => ['Trusted by many', 'Growing community', 'Quality service', 'Customer satisfaction'],
                'order' => 10,
                'status' => true,
                'service_type' => 'stat',
                'stat_number' => '500K+',
                'stat_label' => 'Customers',
                'stat_description' => 'Satisfied Clients',
            ],
            [
                'title' => 'Assets',
                'description' => 'Total assets under management showcasing our financial strength.',
                'icon' => 'TrendingUp',
                'products' => [],
                'cta_text' => 'Learn More',
                'cta_link' => '/about-us',
                'color' => 'from-green-600 to-green-800',
                'benefits' => ['Financial strength', 'Stable growth', 'Secure investments'],
                'order' => 11,
                'status' => true,
                'service_type' => 'stat',
                'stat_number' => 'Rs 50B+',
                'stat_label' => 'Assets',
                'stat_description' => 'Total Assets',
            ],
            [
                'title' => 'Experience',
                'description' => 'Decades of banking excellence serving the people of AJK.',
                'icon' => 'Shield',
                'products' => [],
                'cta_text' => 'Our History',
                'cta_link' => '/about-us',
                'color' => 'from-blue-600 to-blue-800',
                'benefits' => ['Trusted legacy', 'Proven track record', 'Experienced team'],
                'order' => 12,
                'status' => true,
                'service_type' => 'stat',
                'stat_number' => '50+',
                'stat_label' => 'Years',
                'stat_description' => 'Banking Excellence',
            ],
        ];

        foreach ($services as $service) {
            BankService::create($service);
        }
    }
}
