name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug
          extensions: pdo, pdo_sqlite, sqlite3, mbstring, zip, exif, pcntl, bcmath, gd

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Set Required Environment Variables
        run: |
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=:memory:" >> .env
          echo "BANK_BRANCHES_COUNT=87" >> .env
          echo "CONTACT_PHONE=\"+92-5816-123456\"" >> .env
          echo "CONTACT_EMAIL=\"info@bajk.com\"" >> .env
          echo "CONTACT_ADDRESS=\"Test Address\"" >> .env
          echo "MARQUEE_ACHIEVEMENT_TEXT=\"Test Achievement\"" >> .env
          echo "MARQUEE_SERVICES_TEXT=\"Test Services\"" >> .env
          echo "MARQUEE_SUPPORT_TEXT=\"Test Support\"" >> .env
          echo "MARQUEE_DIGITAL_TEXT=\"Test Digital\"" >> .env
          echo "MARQUEE_CONTACT_TEXT=\"Test Contact\"" >> .env
          echo "MARQUEE_NETWORK_TEXT=\"Test Network\"" >> .env

      - name: Clear Caches
        run: |
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          php artisan cache:clear

      - name: Tests
        run: ./vendor/bin/pest
